site_name: AI Lang Stuff
site_description: Local-first AI experimentation toolkit with LangChain, LangGraph, and Ollama
site_author: AI Lang Stuff Team
repo_url: https://github.com/yourusername/ai-lang-stuff
repo_name: ai-lang-stuff

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

nav:
  - Home: README.md
  - Getting Started:
    - Quickstart: QUICKSTART.md
    - Installation: README.md#installation
    - Configuration: README.md#configuration
  - Development:
    - Development Plan: docs/DEVELOPMENT-PLAN-20-POINTS.md
    - Phase 2 Plan: docs/DEVELOPMENT-PLAN-PHASE-2.md
    - Project Status: PROJECT_STATUS.md
    - Implementation Summary: IMPLEMENTATION_SUMMARY.md
  - Examples:
    - Overview: examples/README.md
  - Contributing:
    - Guidelines: README.md#contributing
    - Code Quality: README.md#code-quality

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/ai-lang-stuff
