name: Performance Benchmarks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for comparison

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Ollama
      run: |
        curl -fsSL https://ollama.ai/install.sh | sh
        ollama serve &
        sleep 5

    - name: Pull benchmark models
      run: |
        ollama pull qwen2.5:0.5b
        ollama list

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        uv venv
        source .venv/bin/activate
        uv pip install -e ".[dev]"
        uv pip install pytest-benchmark

    - name: Run benchmarks
      run: |
        source .venv/bin/activate
        pytest tests/benchmarks/ --benchmark-only --benchmark-json=benchmark-results.json
      env:
        OLLAMA_BASE_URL: http://localhost:11434

    - name: Store benchmark results
      uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: 'pytest'
        output-file-path: benchmark-results.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: false
        alert-threshold: '150%'
        comment-on-alert: true
        fail-on-alert: false

    - name: Compare with baseline
      if: github.event_name == 'pull_request'
      run: |
        echo "## Benchmark Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Benchmark comparison against base branch:" >> $GITHUB_STEP_SUMMARY
        source .venv/bin/activate
        python scripts/compare_benchmarks.py >> $GITHUB_STEP_SUMMARY || echo "No baseline found" >> $GITHUB_STEP_SUMMARY

    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: benchmark-results.json
