name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        uv venv
        source .venv/bin/activate
        uv pip install ruff black mypy

    - name: Run Ruff linter
      run: |
        source .venv/bin/activate
        ruff check src/ examples/ tests/ --output-format=github

    - name: Run Ruff formatter check
      run: |
        source .venv/bin/activate
        ruff format --check src/ examples/ tests/

    # Black disabled - using ruff-format as the primary formatter
    # - name: Run Black formatter check
    #   run: |
    #     source .venv/bin/activate
    #     black --check src/ examples/ tests/

    - name: Run mypy type checking
      run: |
        source .venv/bin/activate
        mypy src/ --install-types --non-interactive || true
      continue-on-error: true

    - name: Check import sorting
      run: |
        source .venv/bin/activate
        ruff check --select I src/ examples/ tests/
